# Generated by Django 2.2 on 2021-11-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retriever', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsnippet',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_tag', to='retriever.Tag'),
        ),
    ]
