# Generated by Django 2.2 on 2021-11-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retriever', '0002_auto_20211128_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsnippet',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
